/**
 * Reports for one simulation, or a comparison of 2–4, as .md or .pdf.
 *
 * The report is always built once, as Markdown (plain GitHub/Notion-flavoured:
 * headings, tables, bullet lists). The .md button downloads it directly in the
 * browser; the .pdf button sends the same Markdown to the backend, which
 * styles it and returns a PDF. So both files always say exactly the same thing.
 *
 * Aim: everything someone needs to understand and trust a run, in an
 * order that reads top-down — headline numbers, what happened, why,
 * then the supporting detail, then how it was computed.
 */

import {
  fullTitle, runLabel, conditionLine, formatDateTime, formatGrowth,
  growthStateLabel, percentOfReference, REFERENCE_GROWTH_RATE, REFERENCE_CONDITION, GROWTH_UNIT,
} from "@/lib/sim-format";
import { keyFluxes, interpretRun, energyMode, fmtFlux, hasFluxData, FLUX_UNIT, type KeyFluxes } from "@/lib/flux-summary";
import { pathwayDiff, fmtPathway, allOf, type PathwayRow } from "@/lib/pathway-diff";

interface ExpressionRow {
  gene_id: string;
  gene_name?: string | null;
  relative_expression: number;
  confidence: number;
  prediction_source?: string | null;
  reference_tpm?: number | null;
}

export interface ExportableSim {
  id: string;
  run_number?: number | null;
  name?: string | null;
  status: string;
  temperature: number;
  ph: number;
  oxygen_level: string;
  carbon_source: string;
  nitrogen_source: string;
  growth_rate: number | null;
  doubling_time: number | null;
  viability_score: number | null;
  compute_time_ms: number | null;
  created_at: string | null;
  infeasibility_reason?: string | null;
  expression_results?: ExpressionRow[] | null;
  flux_distribution?: Record<string, number> | null;
  fba_results?: {
    active_pathways?: string[];
    bottlenecks?: string[];
    bottleneck_names?: Record<string, string> | null;
    pathway_fluxes?: Record<string, number> | null;
    regulator_state?: Record<string, boolean> | null;
    tf_state_changes?: Record<string, string> | null;
    expression_summary?: {
      genes_up?: number;
      genes_down?: number;
      total_genes_evaluated?: number;
      genes_by_source?: Record<string, number> | null;
    } | null;
  } | null;
  model_versions?: Record<string, string> | null;
}

/* ─── Small helpers ─────────────────────────────────────────── */

const REFERENCE = { temperature: 37, ph: 7, oxygen_level: "aerobic", carbon_source: "glucose", nitrogen_source: "ammonium" };
const FOOTER = "*Generated by GENESIS — a flight simulator for synthetic biology.*";

/** Markdown table from a header row and body rows. */
function table(header: string[], rows: string[][], align?: ("l" | "r")[]): string[] {
  const sep = header.map((_, i) => (align?.[i] === "r" ? "---:" : "---"));
  return [`| ${header.join(" | ")} |`, `| ${sep.join(" | ")} |`, ...rows.map((r) => `| ${r.join(" | ")} |`)];
}

const pctText = (v: number | null | undefined) => (v != null ? `${(v * 100).toFixed(0)}%` : "—");
const doublingText = (d: number | null | undefined) => (d != null ? `${d.toFixed(2)} h` : "no growth");
const seconds = (ms: number | null | undefined) => (ms != null ? `${(ms / 1000).toFixed(1)} s` : "—");
const geneLabel = (e: ExpressionRow) => (e.gene_name ? `*${e.gene_name}*` : e.gene_id);

/* ─── File names ───────────────────────────────────────────────
 * genesis-run-145-glucose-anaerobic-31c.md      (no custom name)
 * genesis-run-60-heat-shock-test.md             (custom name)
 * genesis-compare-145-144-143-2026-10-11.md     (comparison, local date)
 */

/** "Heat shock test!" -> "heat-shock-test": lowercase, a–z/0–9 joined by "-", max ~40 chars. */
function slugify(text: string, max = 40): string {
  const slug = text
    .normalize("NFKD").replace(/[\u0300-\u036f]/g, "") // é -> e
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")                         // spaces, °, ·, / ... -> "-"
    .replace(/^-+|-+$/g, "");
  if (slug.length <= max) return slug;
  const cut = slug.slice(0, max);
  return cut.includes("-") ? cut.slice(0, cut.lastIndexOf("-")) : cut; // don't end mid-word
}

function runFileName(sim: ExportableSim): string {
  const label = sim.name?.trim()
    ? slugify(sim.name)
    : slugify(`${sim.carbon_source} ${sim.oxygen_level} ${sim.temperature}c`);
  const id = sim.run_number != null ? `run-${sim.run_number}` : `simulation-${sim.id.slice(0, 8)}`;
  return `genesis-${[id, label].filter(Boolean).join("-")}.md`;
}

function compareFileName(sims: ExportableSim[]): string {
  const ids = sims.map((s) => s.run_number ?? s.id.slice(0, 4)).join("-");
  const d = new Date();
  const date = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  return `genesis-compare-${ids}-${date}.md`;
}

export interface Report {
  markdown: string;
  filename: string; // ends in .md; the PDF uses the same name with .pdf
}

const API = "http://localhost:8000/api/v1";

/** Save a Blob to the user's Downloads with the given name. */
function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Ask the backend to turn the report into a PDF, then download it. Throws with a readable message on failure. */
async function downloadPdf(report: Report) {
  const filename = report.filename.replace(/\.md$/, ".pdf");
  const res = await fetch(`${API}/export/pdf`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ markdown: report.markdown, filename }),
  });
  if (!res.ok) {
    const detail = await res.json().then((d) => d.detail).catch(() => null);
    throw new Error(typeof detail === "string" ? detail : `PDF export failed (${res.status})`);
  }
  saveBlob(await res.blob(), filename);
}

function download(content: string, filename: string) {
  saveBlob(new Blob([content], { type: "text/markdown;charset=utf-8" }), filename);
}

/** Rows for the carbon/energy flow table, shared by both reports. */
function fluxRows(carbon: string, ks: KeyFluxes[]): [string, string[]][] {
  const rows: [string, string[]][] = [
    [`Carbon uptake (${carbon})`, ks.map((k) => k.carbonUptake.toFixed(1))],
    ["Oxygen uptake", ks.map((k) => k.oxygenUptake.toFixed(1))],
    ["Glycolysis, GAPD (← = reverse)", ks.map((k) => fmtFlux(k.glycolysis))],
    ["Pentose phosphate entry, G6PDH2r", ks.map((k) => k.pppOxidative.toFixed(1))],
    ["Pyruvate → acetyl-CoA with O₂, PDH", ks.map((k) => k.pdh.toFixed(1))],
    ["Pyruvate → acetyl-CoA + formate, PFL", ks.map((k) => k.pfl.toFixed(1))],
    ["TCA cycle entry, citrate synthase", ks.map((k) => k.tcaEntry.toFixed(1))],
  ];
  if (ks.some((k) => k.glyoxylateShunt > 0.05)) rows.push(["Glyoxylate shunt, ICL", ks.map((k) => k.glyoxylateShunt.toFixed(1))]);
  rows.push(["Products secreted (total)", ks.map((k) => k.productTotal.toFixed(1))]);
  rows.push(["CO₂ released", ks.map((k) => k.co2Release.toFixed(1))]);
  return rows;
}

/** "▲ 2.67× (11): pflB, focA, …" — every stored gene, grouped by fold. */
function geneTiers(rows: ExpressionRow[], direction: "up" | "down", perTier = 12): string[] {
  const picked = rows.filter((e) => (direction === "up" ? e.relative_expression > 1.01 : e.relative_expression < 0.99));
  const tiers = new Map<string, ExpressionRow[]>();
  for (const e of picked) {
    const key = e.relative_expression.toFixed(2);
    tiers.set(key, [...(tiers.get(key) ?? []), e]);
  }
  const keys = Array.from(tiers.keys()).sort((a, b) => (direction === "up" ? +b - +a : +a - +b));
  return keys.map((k) => {
    const genes = tiers.get(k)!;
    const names = genes.slice(0, perTier).map(geneLabel).join(", ");
    const more = genes.length > perTier ? `, +${genes.length - perTier} more` : "";
    return `- ${direction === "up" ? "▲" : "▼"} **${k}×** (${genes.length}): ${names}${more}`;
  });
}

function methodLines(s: ExportableSim): string[] {
  const mv = s.model_versions ?? {};
  return [
    `- **Metabolic model:** ${mv.metabolic_model ?? "iML1515"} (*E. coli* K-12 MG1655), solved by flux balance analysis${mv.solver ? ` with ${mv.solver}` : ""}${mv.cobra ? ` (COBRApy ${mv.cobra})` : ""}`,
    `- **Expression predictor:** ${mv.predictor ?? "unknown"}`,
    `- **Reference for "vs reference":** ${REFERENCE_GROWTH_RATE} ${GROWTH_UNIT} under ${REFERENCE_CONDITION}`,
    `- **Units:** fluxes in ${FLUX_UNIT}; growth in ${GROWTH_UNIT}. FBA returns one optimal solution; other equally good flux routes can exist.`,
  ];
}

/* ─── Single run ────────────────────────────────────────────── */

export function buildSimulationReport(sim: ExportableSim): Report {
  const fba = sim.fba_results ?? {};
  const pct = percentOfReference(sim.growth_rate);
  const L: string[] = [];

  L.push(`# ${fullTitle(sim)}`, "");
  L.push(`> GENESIS simulation report · ${formatDateTime(sim.created_at)}${sim.name ? ` · ${conditionLine(sim)}` : ""}`, "");

  // At a glance
  L.push("## At a glance", "");
  L.push(...table(
    ["Growth rate", "Doubling time", "Viability", "Vs reference"],
    [[`**${formatGrowth(sim.growth_rate)}**`, doublingText(sim.doubling_time), pctText(sim.viability_score),
      `${growthStateLabel(sim.status)}${pct != null ? ` · ${pct}%` : ""}`]],
  ), "");
  const story = interpretRun({ ...sim, tf_state_changes: fba.tf_state_changes });
  if (story.length) L.push("**What happened**", "", ...story.map((s) => `- ${s}`), "");

  // Conditions vs reference
  L.push("## Conditions", "");
  const condRows: [string, string, string][] = [
    ["Temperature", `${sim.temperature} °C`, `${REFERENCE.temperature} °C`],
    ["pH", `${sim.ph}`, `${REFERENCE.ph}`],
    ["Oxygen", sim.oxygen_level, REFERENCE.oxygen_level],
    ["Carbon source", sim.carbon_source, REFERENCE.carbon_source],
    ["Nitrogen source", sim.nitrogen_source, REFERENCE.nitrogen_source],
  ];
  L.push(...table(["Parameter", "This run", "Reference"],
    condRows.map(([p, v, r]) => [p, v === r ? v : `**${v}**`, r])), "");
  L.push("Values in bold differ from the reference condition.", "");

  // Carbon and energy flow
  if (hasFluxData(sim.flux_distribution)) {
    const k = keyFluxes(sim.flux_distribution, sim.carbon_source);
    L.push("## Carbon and energy flow", "");
    L.push(`Energy mode: **${energyMode(k)}**. Fluxes in ${FLUX_UNIT}.`, "");
    L.push(...table(["Step", "Flux"], fluxRows(sim.carbon_source, [k]).map(([label, v]) => [label, v[0]]), ["l", "r"]), "");
    if (k.products.length) {
      L.push(`**Secreted:** ${k.products.map((p) => `${p.name} ${p.value.toFixed(1)}`).join(" · ")}`, "");
    }
  }

  // Gene expression
  const expr = sim.expression_results ?? [];
  const es = fba.expression_summary;
  if (expr.length || es) {
    L.push("## Gene expression", "");
    if (es?.total_genes_evaluated) {
      const sources = Object.entries(es.genes_by_source ?? {}).map(([k, v]) => `${v.toLocaleString()} ${k}`).join(" · ");
      L.push(`${es.total_genes_evaluated.toLocaleString()} genes evaluated: **${es.genes_up ?? 0} up**, **${es.genes_down ?? 0} down** versus the reference${sources ? ` (predicted by: ${sources})` : ""}.`, "");
    }
    const confs = Array.from(new Set(expr.map((e) => e.confidence)));
    if (confs.length === 1) L.push(`All listed genes carry ${(confs[0] * 100).toFixed(0)}% confidence.`, "");
    const up = geneTiers(expr, "up");
    const down = geneTiers(expr, "down");
    if (up.length) L.push("**Increased**", "", ...up, "");
    if (down.length) L.push("**Decreased**", "", ...down, "");
    if (es && (es.genes_up ?? 0) + (es.genes_down ?? 0) > expr.length) {
      L.push(`Only the most-changed genes are saved with a run, so the lists above are the top of the full set.`, "");
    }
  }

  // Regulators
  const regs = Object.entries(fba.regulator_state ?? {});
  if (regs.length) {
    const changed = fba.tf_state_changes ?? {};
    L.push("## Master regulators", "");
    L.push(...table(["Regulator", "State", "Vs reference"],
      regs.sort(([a], [b]) => a.localeCompare(b)).map(([tf, on]) => [tf, on ? "on" : "off", changed[tf] ? `**switched ${changed[tf]}**` : "same"])), "");
  }

  // Pathways
  const pf = Object.entries(fba.pathway_fluxes ?? {});
  if (pf.length) {
    L.push("## Busiest pathways", "");
    L.push(`Total flux through each pathway (sum of its reactions, ${FLUX_UNIT}). ${pf.length} pathways carry flux; the top 10:`, "");
    L.push(...table(["Pathway", "Total flux"], pf.slice(0, 10).map(([p, v]) => [p, fmtPathway(v, true)]), ["l", "r"]), "");
  } else if (fba.active_pathways?.length) {
    L.push("## Main pathways", "", fba.active_pathways.join(" · "), "");
  }

  // Bottlenecks
  if (fba.bottlenecks?.length) {
    L.push("## Limiting reactions", "");
    L.push("Reactions running at the limit set for them in this simulation — the constraints that shape this solution.", "");
    L.push(...table(["Reaction", "Name"], fba.bottlenecks.map((b) => [`\`${b}\``, fba.bottleneck_names?.[b] ?? "—"])), "");
  }

  // Method
  L.push("## Method", "", ...methodLines(sim));
  L.push(`- **Computed in:** ${seconds(sim.compute_time_ms)} · run ID \`${sim.id}\``, "");
  L.push("---", "", FOOTER, "");

  return { markdown: L.join("\n"), filename: runFileName(sim) };
}

export function exportSimulationMarkdown(sim: ExportableSim) {
  const report = buildSimulationReport(sim);
  download(report.markdown, report.filename);
}

export async function exportSimulationPdf(sim: ExportableSim) {
  await downloadPdf(buildSimulationReport(sim));
}

/* ─── Comparison of 2–4 runs ────────────────────────────────── */

/** Bold the best value in a row (highest or lowest), ignoring missing ones. */
function boldBest(values: (number | null)[], text: string[], best: "max" | "min"): string[] {
  const nums = values.filter((v): v is number => v != null);
  if (nums.length < 2) return text;
  const target = best === "max" ? Math.max(...nums) : Math.min(...nums);
  return text.map((t, i) => (values[i] === target ? `**${t}**` : t));
}

export function buildComparisonReport(sims: ExportableSim[], letters = ["A", "B", "C", "D"]): Report {
  const L: string[] = [];
  const cols = sims.map((s, i) => `${letters[i]}${s.run_number != null ? ` · ${runLabel(s)}` : ""}`);
  const short = sims.map((s, i) => `${letters[i]} (${runLabel(s) || s.id.slice(0, 8)})`);

  L.push(`# Comparing ${sims.length} simulations`, "");
  L.push(`> GENESIS comparison report · ${formatDateTime(new Date().toISOString())}`, "");

  // Runs
  L.push("## Runs", "");
  L.push(...table(["", "Run", "Name", "Conditions", "Date"],
    sims.map((s, i) => [`**${letters[i]}**`, runLabel(s) || "—", s.name?.trim() || "—", conditionLine(s) + ` · ${s.nitrogen_source}`, formatDateTime(s.created_at)])), "");

  // Key findings
  const growths = sims.map((s) => s.growth_rate ?? 0);
  const fastest = growths.indexOf(Math.max(...growths));
  const slowest = growths.indexOf(Math.min(...growths));
  const ks = sims.map((s) => (hasFluxData(s.flux_distribution) ? keyFluxes(s.flux_distribution, s.carbon_source) : null));
  const diff = pathwayDiff(sims);
  const condKeys: [string, (s: ExportableSim) => string][] = [
    ["temperature", (s) => `${s.temperature} °C`], ["pH", (s) => `${s.ph}`], ["oxygen", (s) => s.oxygen_level],
    ["carbon source", (s) => s.carbon_source], ["nitrogen source", (s) => s.nitrogen_source],
  ];
  const varying = condKeys.filter(([, get]) => new Set(sims.map(get)).size > 1);
  const constant = condKeys.filter(([, get]) => new Set(sims.map(get)).size === 1);

  L.push("## Key findings", "");
  if (growths[fastest] > 0) {
    const ratio = growths[slowest] > 0.01 ? ` — ${(growths[fastest] / growths[slowest]).toFixed(1)}× the slowest, ${short[slowest]} at ${formatGrowth(growths[slowest])}` : "";
    L.push(`- **Fastest:** ${short[fastest]} at ${formatGrowth(growths[fastest])}${ratio}.`);
  }
  if (varying.length) {
    L.push(`- **What differs:** ${varying.map(([k]) => k).join(", ")}.${constant.length ? ` Same in all: ${constant.map(([k, get]) => `${k} ${get(sims[0])}`).join(", ")}.` : ""}`);
  } else {
    L.push("- **Conditions are identical** — any differences come from the DNA input or model changes between runs.");
  }
  if (ks.every(Boolean)) {
    L.push(`- **Energy:** ${sims.map((_, i) => `${letters[i]} ${energyMode(ks[i]!)}`).join(" · ")}.`);
  }
  L.push(`- **Pathways:** ${diff.shared.length} run in ${allOf(sims.length)}; ${diff.switched.length} ${diff.switched.length === 1 ? "is" : "are"} switched on in some and off in others${diff.exact ? `; ${diff.bigChanges.length} shared pathways shift by 2× or more beyond what the growth difference explains` : ""}.`);
  const regDiff = regulatorDiff(sims);
  if (regDiff.length) L.push(`- **Regulators that differ:** ${regDiff.map(([tf]) => tf).join(", ")}.`);
  L.push("");

  // Growth
  L.push("## Growth", "");
  L.push(...table(["", ...cols], [
    ["Growth rate (h⁻¹)", ...boldBest(sims.map((s) => s.growth_rate), sims.map((s) => formatGrowth(s.growth_rate, false)), "max")],
    ["Vs reference", ...sims.map((s) => { const p = percentOfReference(s.growth_rate); return p != null ? `${p}%` : "—"; })],
    ["Growth state", ...sims.map((s) => growthStateLabel(s.status))],
    ["Doubling time (h)", ...boldBest(sims.map((s) => s.doubling_time), sims.map((s) => (s.doubling_time != null ? s.doubling_time.toFixed(2) : "no growth")), "min")],
    ["Viability", ...sims.map((s) => pctText(s.viability_score))],
  ]), "");
  L.push("Best value in each row in bold.", "");

  // Conditions
  L.push("## Conditions", "");
  L.push(...table(["", ...cols, "Reference"], condKeys.map(([k, get]) => {
    const differs = new Set(sims.map(get)).size > 1;
    const ref = k === "temperature" ? "37 °C" : k === "pH" ? "7" : k === "oxygen" ? "aerobic" : k === "carbon source" ? "glucose" : "ammonium";
    return [differs ? `**${k}**` : k, ...sims.map(get), ref];
  })), "");

  // Carbon and energy flow
  if (ks.every(Boolean)) {
    L.push("## Carbon and energy flow", "");
    L.push(`Fluxes in ${FLUX_UNIT}. Carbon uptake is the nutrient each run was given.`, "");
    const rows = fluxRows("nutrient", ks as KeyFluxes[]).map(([label, v]) => [label, ...v]);
    rows.push(["Energy mode", ...ks.map((k) => energyMode(k!))]);
    L.push(...table(["Step", ...cols], rows, ["l", ...cols.map(() => "r" as const)]), "");
  }

  // Pathway differences
  L.push("## Pathway differences", "");
  if (!diff.exact) {
    L.push("Some runs have no saved fluxes, so this compares their top-15 pathway lists (✓ = listed), which is not the same as switched on.", "");
  }
  const pathwayTable = (rows: PathwayRow[], ratio: boolean) =>
    table(["Pathway", ...cols, ...(ratio ? ["Beyond growth"] : [])],
      rows.map((r) => {
        const top = Math.max(...r.values);
        return [r.pathway, ...r.values.map((v) => (diff.exact && v === top ? `**${fmtPathway(v, true)}**` : fmtPathway(v, diff.exact))), ...(ratio ? [`${r.ratio!.toFixed(1)}×`] : [])];
      }), ["l", ...cols.map(() => "r" as const), ...(ratio ? ["r" as const] : [])]);

  L.push("### Switched on or off", "");
  if (diff.switched.length) {
    L.push(diff.exact ? `Total pathway flux (${FLUX_UNIT}); — means no flux.` : "", "");
    L.push(...pathwayTable(diff.switched, false), "");
  } else {
    L.push(`None — every pathway runs in ${allOf(sims.length)} simulations.`, "");
  }
  if (diff.exact) {
    L.push("### Biggest changes among shared pathways", "");
    if (diff.bigChanges.length) {
      L.push(diff.growthAdjusted
        ? "Running in every simulation, but differing at least 2× even after allowing for growth (a faster-growing cell builds more of everything). Values are raw totals; *Beyond growth* is the max ÷ min of flux per unit growth."
        : "Running everywhere, but the busiest run carries at least twice the flux of the quietest.", "");
      L.push(...pathwayTable(diff.bigChanges, true), "");
    } else {
      L.push("No shared pathway differs by 2× or more beyond the growth difference.", "");
    }
  }
  if (diff.shared.length) L.push(`**Running in ${allOf(sims.length)} (${diff.shared.length}):** ${diff.shared.join(" · ")}`, "");

  // Regulators
  if (regDiff.length) {
    L.push("## Regulators that differ", "");
    L.push(...table(["Regulator", ...cols], regDiff.map(([tf, states]) => [tf, ...states])), "");
    L.push("— means that regulator was not reported for the run.", "");
  }

  // Gene expression
  if (sims.some((s) => s.fba_results?.expression_summary || s.expression_results?.length)) {
    L.push("## Gene expression", "");
    const topGene = (s: ExportableSim, dir: "up" | "down") => {
      const rows = (s.expression_results ?? []).filter((e) => (dir === "up" ? e.relative_expression > 1.01 : e.relative_expression < 0.99));
      if (!rows.length) return "—";
      const best = rows.reduce((a, b) => (dir === "up" ? (b.relative_expression > a.relative_expression ? b : a) : (b.relative_expression < a.relative_expression ? b : a)));
      return `${geneLabel(best)} ${best.relative_expression.toFixed(2)}×`;
    };
    L.push(...table(["", ...cols], [
      ["Genes up", ...sims.map((s) => `${s.fba_results?.expression_summary?.genes_up ?? "—"}`)],
      ["Genes down", ...sims.map((s) => `${s.fba_results?.expression_summary?.genes_down ?? "—"}`)],
      ["Most increased", ...sims.map((s) => topGene(s, "up"))],
      ["Most decreased", ...sims.map((s) => topGene(s, "down"))],
    ]), "");
    const common = genesChangedInAll(sims);
    if (common.length) L.push(`**Changed the same way in every run (${common.length}):** ${common.slice(0, 20).join(", ")}${common.length > 20 ? ", …" : ""}`, "");
  }

  // Method
  L.push("## Method", "", ...methodLines(sims[0]));
  L.push(`- **Run IDs:** ${sims.map((s, i) => `${letters[i]} \`${s.id}\``).join(" · ")}`, "");
  L.push("---", "", FOOTER, "");

  return { markdown: L.join("\n"), filename: compareFileName(sims) };
}

export function exportComparisonMarkdown(sims: ExportableSim[], letters?: string[]) {
  const report = buildComparisonReport(sims, letters);
  download(report.markdown, report.filename);
}

export async function exportComparisonPdf(sims: ExportableSim[], letters?: string[]) {
  await downloadPdf(buildComparisonReport(sims, letters));
}

/** Master regulators whose on/off state is not the same in every run. */
function regulatorDiff(sims: ExportableSim[]): [string, string[]][] {
  const names = Array.from(new Set(sims.flatMap((s) => Object.keys(s.fba_results?.regulator_state ?? {})))).sort();
  return names
    .map((tf) => [tf, sims.map((s) => {
      const v = s.fba_results?.regulator_state?.[tf];
      return v == null ? "—" : v ? "on" : "off";
    })] as [string, string[]])
    .filter(([, states]) => new Set(states).size > 1);
}

/** Genes in every run's saved list, moving the same direction in all. */
function genesChangedInAll(sims: ExportableSim[]): string[] {
  const maps = sims.map((s) => new Map((s.expression_results ?? []).map((e) => [e.gene_id, e])));
  const first = maps[0];
  const out: string[] = [];
  first.forEach((e, id) => {
    const dir = e.relative_expression > 1 ? 1 : -1;
    if (maps.every((m) => { const x = m.get(id); return x && (x.relative_expression > 1 ? 1 : -1) === dir && Math.abs(x.relative_expression - 1) > 0.01; })) {
      out.push(`${geneLabel(e)} ${dir > 0 ? "▲" : "▼"}`);
    }
  });
  return out;
}