import { fullTitle, runLabel, simTitle, formatDateTime, formatGrowth } from "@/lib/sim-format";

/**
 * Export a simulation result as Notion-compatible Markdown.
 * Downloads as .md file via browser Blob API — no server needed.
 */

interface ExportableSim {
  id: string;
  run_number?: number | null;
  name?: string | null;
  status: string;
  temperature: number;
  ph: number;
  oxygen_level: string;
  carbon_source: string;
  nitrogen_source: string;
  growth_rate: number | null;
  doubling_time: number | null;
  viability_score: number | null;
  compute_time_ms: number | null;
  created_at: string | null;
  expression_results?: { gene_id: string; relative_expression: number; confidence: number }[] | null;
  fba_results?: { active_pathways: string[]; bottlenecks: string[] } | null;
  model_versions?: Record<string, string> | null;
}

export function exportSimulationMarkdown(sim: ExportableSim) {
  const date = formatDateTime(sim.created_at ?? new Date().toISOString());

  const lines: string[] = [
    `# GENESIS Simulation Report — ${fullTitle(sim)}`,
    ``,
    `**Date:** ${date}`,
    `**Status:** ${sim.status}`,
    `**Model:** ${sim.model_versions?.predictor || "unknown"}`,
    `**Compute Time:** ${sim.compute_time_ms ?? "N/A"} ms`,
    ``,
    `---`,
    ``,
    `## Environmental Conditions`,
    ``,
    `| Parameter | Value |`,
    `|-----------|-------|`,
    `| Temperature | ${sim.temperature}°C |`,
    `| pH | ${sim.ph} |`,
    `| Oxygen | ${sim.oxygen_level} |`,
    `| Carbon Source | ${sim.carbon_source} |`,
    `| Nitrogen Source | ${sim.nitrogen_source} |`,
    ``,
    `---`,
    ``,
    `## Results`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Growth Rate | ${formatGrowth(sim.growth_rate)} |`,
    `| Doubling Time | ${sim.doubling_time != null ? `${sim.doubling_time.toFixed(2)} h` : "N/A"} |`,
    `| Viability | ${sim.viability_score != null ? `${(sim.viability_score * 100).toFixed(0)}%` : "N/A"} |`,
    ``,
  ];

  // Active pathways
  const pathways = sim.fba_results?.active_pathways;
  if (pathways && pathways.length > 0) {
    lines.push(`## Active Metabolic Pathways`, ``);
    pathways.forEach((p, i) => lines.push(`${i + 1}. ${p}`));
    lines.push(``);
  }

  // Expression predictions
  const expr = sim.expression_results;
  if (expr && expr.length > 0) {
    lines.push(`## Expression Predictions`, ``);
    lines.push(`| Gene | Relative Expression | Confidence |`);
    lines.push(`|------|---------------------|------------|`);
    expr.forEach((e) => {
      lines.push(`| ${e.gene_id} | ${e.relative_expression.toFixed(2)}× | ${(e.confidence * 100).toFixed(0)}% |`);
    });
    lines.push(``);
  }

  // Bottlenecks
  const bottlenecks = sim.fba_results?.bottlenecks;
  if (bottlenecks && bottlenecks.length > 0) {
    lines.push(`## Bottleneck Reactions`, ``);
    bottlenecks.forEach((b) => lines.push(`- ⚠ ${b}`));
    lines.push(``);
  }

  lines.push(`---`, ``, `*Generated by GENESIS — A flight simulator for synthetic biology*`);

  // Download
  const content = lines.join("\n");
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  // e.g. genesis-run-12.md (falls back to the id for rows without a number)
  a.download = sim.run_number != null ? `genesis-run-${sim.run_number}.md` : `genesis-simulation-${sim.id.slice(0, 8)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}


/**
 * Export a comparison of multiple simulations as Notion-compatible Markdown.
 */
export function exportComparisonMarkdown(sims: ExportableSim[]) {
  // Column headings use the run number when there is one: "#12", "#15", ...
  const labels = sims.map((s, i) => runLabel(s) || `Sim ${["A", "B", "C", "D"][i]}`);
  const date = formatDateTime(new Date().toISOString());

  const lines: string[] = [
    `# GENESIS Comparison Report`,
    ``,
    `**Date:** ${date}`,
    `**Simulations compared:** ${sims.length}`,
    ``,
    ...sims.map((s, i) => `- **${labels[i]}:** ${simTitle(s)}`),
    ``,
    `---`,
    ``,
    `## Conditions`,
    ``,
    `| | ${labels.join(" | ")} |`,
    `|---|${sims.map(() => "---").join("|")}|`,
    `| Temperature | ${sims.map((s) => `${s.temperature}°C`).join(" | ")} |`,
    `| pH | ${sims.map((s) => `${s.ph}`).join(" | ")} |`,
    `| Oxygen | ${sims.map((s) => s.oxygen_level).join(" | ")} |`,
    `| Carbon | ${sims.map((s) => s.carbon_source).join(" | ")} |`,
    `| Nitrogen | ${sims.map((s) => s.nitrogen_source).join(" | ")} |`,
    ``,
    `---`,
    ``,
    `## Results`,
    ``,
    `| Metric | ${labels.join(" | ")} |`,
    `|--------|${sims.map(() => "---").join("|")}|`,
    `| Growth Rate | ${sims.map((s) => formatGrowth(s.growth_rate)).join(" | ")} |`,
    `| Doubling Time | ${sims.map((s) => s.doubling_time != null ? `${s.doubling_time.toFixed(2)} h` : "N/A").join(" | ")} |`,
    `| Viability | ${sims.map((s) => s.viability_score != null ? `${(s.viability_score * 100).toFixed(0)}%` : "N/A").join(" | ")} |`,
    `| Status | ${sims.map((s) => s.status).join(" | ")} |`,
    ``,
  ];

  // Pathway differences
  if (sims.length >= 2) {
    lines.push(`## Pathway Differences`, ``);
    const sets = sims.map((s) => new Set(s.fba_results?.active_pathways || []));
    sims.forEach((_, i) => {
      if (i === 0) return;
      const onlyA = Array.from(sets[0]).filter((p) => !sets[i].has(p));
      const onlyB = Array.from(sets[i]).filter((p) => !sets[0].has(p));
      const shared = Array.from(sets[0]).filter((p) => sets[i].has(p));
      lines.push(`### ${labels[0]} vs ${labels[i]}`, ``);
      if (onlyA.length > 0) lines.push(`- **Only ${labels[0]}:** ${onlyA.join(", ")}`);
      if (onlyB.length > 0) lines.push(`- **Only ${labels[i]}:** ${onlyB.join(", ")}`);
      if (shared.length > 0) lines.push(`- **Shared (${shared.length}):** ${shared.join(", ")}`);
      lines.push(``);
    });
  }

  lines.push(`---`, ``, `*Generated by GENESIS — A flight simulator for synthetic biology*`);

  const content = lines.join("\n");
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `genesis-comparison-${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}