"""
PDF export.

The frontend already builds each report as Markdown (one run, or a
comparison of 2-4). This endpoint turns that same Markdown into a styled,
A4 PDF, so the .md and .pdf downloads always contain exactly the same
analysis — there is only one report template to maintain.

    Markdown --(python-markdown)--> HTML --(+ print CSS, WeasyPrint)--> PDF

WeasyPrint produces real text (selectable, searchable) and supports
everything the reports use: tables, page numbers, and symbols such as
h⁻¹, CO₂, ▲ ▼ and ←, via the DejaVu fonts installed in the Docker image.
"""

import re

import markdown
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel, Field
from weasyprint import HTML

router = APIRouter()


class PdfRequest(BaseModel):
    markdown: str = Field(..., min_length=1, max_length=500_000)
    filename: str = Field("genesis-report.pdf", max_length=150)


# Print styling. Light background, dark teal accents, compact tables.
REPORT_CSS = """
@page {
  size: A4;
  margin: 15mm 14mm 15mm 14mm;
  @top-left {
    content: string(report-title);
    font-size: 7.5pt; color: #7a8c93;
  }
  @top-right {
    content: "GENESIS";
    font-size: 7.5pt; color: #7a8c93; letter-spacing: 0.12em;
  }
  @bottom-center {
    content: "Page " counter(page) " of " counter(pages);
    font-size: 7.5pt; color: #7a8c93;
  }
}
@page :first { @top-left { content: none; } }

html { font-family: "DejaVu Sans", sans-serif; font-size: 8.9pt; color: #1d2a30; line-height: 1.4; }
body { margin: 0; }

h1 {
  string-set: report-title content();
  font-size: 17pt; line-height: 1.25; color: #0b3d4a;
  margin: 0 0 4pt 0; padding-bottom: 6pt; border-bottom: 2.2pt solid #11a2b4;
}
h2 {
  font-size: 11.2pt; color: #0b3d4a; margin: 13pt 0 5pt 0;
  padding-left: 7pt; border-left: 3pt solid #11a2b4;
  break-after: avoid;
}
h3 { font-size: 10pt; color: #24505c; margin: 11pt 0 4pt 0; break-after: avoid; }

/* Subtitle line under the title ("> GENESIS simulation report · date") */
blockquote { margin: 4pt 0 10pt 0; padding: 0; color: #5c7480; font-size: 8.6pt; }
blockquote p { margin: 0; }

p { margin: 4pt 0 6pt 0; }
ul, ol { margin: 3pt 0 7pt 0; padding-left: 15pt; }
li { margin: 1.5pt 0; }
strong { color: #0b2a33; }
code { font-family: "DejaVu Sans Mono", monospace; font-size: 8pt; background: #eef4f6; padding: 0.5pt 2.5pt; border-radius: 2pt; }
hr { border: none; border-top: 0.6pt solid #c9d6db; margin: 14pt 0 8pt 0; }

table { width: 100%; border-collapse: collapse; margin: 4pt 0 7pt 0; font-size: 8.1pt; }
thead { display: table-header-group; }            /* repeat header on every page */
tr { break-inside: avoid; }
th {
  background: #e3f1f4; color: #0b3d4a; font-weight: bold;
  text-align: left; padding: 3pt 5pt; border-bottom: 1pt solid #9cc5ce;
}
td { padding: 2.4pt 5pt; border-bottom: 0.5pt solid #dfe8eb; vertical-align: top; }
tbody tr:nth-child(even) td { background: #f6fafb; }

/* Keep a heading with what follows it, and short lists in one piece */
h2 + p, h3 + p, p:has(+ ul) { break-after: avoid; }
ul { break-inside: avoid; }

/* The closing "Generated by GENESIS" line */
body > p:last-child { color: #7a8c93; font-size: 8pt; }
"""


def _no_fetch(url: str, *args, **kwargs):
    """The report never needs outside files. Refusing every fetch means a
    crafted Markdown image/link cannot make the server read local files or
    call internal URLs."""
    raise ValueError("external resources are disabled in PDF export")


def _safe_filename(name: str) -> str:
    name = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-.") or "genesis-report"
    if name.lower().endswith(".md"):
        name = name[:-3]
    return name if name.lower().endswith(".pdf") else f"{name}.pdf"


@router.post("/export/pdf")
def export_pdf(body: PdfRequest) -> Response:
    """Turn a report's Markdown into a PDF download.

    Declared with plain `def` (not async) so FastAPI runs it in a worker
    thread: building a PDF takes a moment of CPU and must not pause the
    rest of the API while it does.
    """
    try:
        html_body = markdown.markdown(body.markdown, extensions=["tables", "sane_lists"])
        page = (
            '<!doctype html><html><head><meta charset="utf-8">'
            f"<style>{REPORT_CSS}</style></head><body>{html_body}</body></html>"
        )
        pdf = HTML(string=page, url_fetcher=_no_fetch).write_pdf()
    except Exception as exc:  # pragma: no cover - surfaced to the UI as a message
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}") from exc

    return Response(
        content=pdf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{_safe_filename(body.filename)}"'},
    )