"""sync schema with models

Revision ID: 23bb1ea20629
Revises: 8900aeb919ac
Create Date: 2026-09-05 18:35:45.389113
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bb1ea20629'
down_revision: Union[str, None] = '8900aeb919ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enzyme_kinetics', sa.Column('substrate', sa.String(length=200), nullable=True))
    op.add_column('enzyme_kinetics', sa.Column('specific_activity', sa.Float(), nullable=True))
    op.add_column('enzyme_kinetics', sa.Column('source_db', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enzyme_kinetics', 'source_db')
    op.drop_column('enzyme_kinetics', 'specific_activity')
    op.drop_column('enzyme_kinetics', 'substrate')
    # ### end Alembic commands ###
