"""allow null reaction_id in enzyme_kinetics

Revision ID: 3de98aed79d4
Revises: 23bb1ea20629
Create Date: 2026-09-05 18:47:32.543395
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de98aed79d4'
down_revision: Union[str, None] = '23bb1ea20629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enzyme_kinetics', 'reaction_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enzyme_kinetics', 'reaction_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
