"""create_all_tables

Revision ID: 8900aeb919ac
Revises: 
Create Date: 2026-09-01 18:52:06.643056
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8900aeb919ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_sequence', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('locus_tag', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=500), nullable=True),
    sa.Column('start_pos', sa.Integer(), nullable=False),
    sa.Column('end_pos', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=1), nullable=False),
    sa.Column('dna_sequence', sa.Text(), nullable=True),
    sa.Column('protein_sequence', sa.Text(), nullable=True),
    sa.Column('cog_category', sa.String(length=10), nullable=True),
    sa.Column('gc_content', sa.Float(), nullable=True),
    sa.Column('length_bp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gene_product_fts', 'genes', ['product'], unique=False)
    op.create_index(op.f('ix_genes_locus_tag'), 'genes', ['locus_tag'], unique=True)
    op.create_index(op.f('ix_genes_name'), 'genes', ['name'], unique=False)
    op.create_table('genetic_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('part_type', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('source_registry', sa.String(length=50), nullable=True),
    sa.Column('registry_id', sa.String(length=100), nullable=True),
    sa.Column('measured_strength', sa.Float(), nullable=True),
    sa.Column('measurement_unit', sa.String(length=50), nullable=True),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sbol_uri', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genetic_parts_name'), 'genetic_parts', ['name'], unique=False)
    op.create_index(op.f('ix_genetic_parts_part_type'), 'genetic_parts', ['part_type'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bigg_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('subsystem', sa.String(length=200), nullable=True),
    sa.Column('reaction_formula', sa.String(length=1000), nullable=True),
    sa.Column('default_lower_bound', sa.Float(), nullable=False),
    sa.Column('default_upper_bound', sa.Float(), nullable=False),
    sa.Column('is_reversible', sa.Boolean(), nullable=False),
    sa.Column('ec_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactions_bigg_id'), 'reactions', ['bigg_id'], unique=True)
    op.create_table('transcription_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('regulondb_id', sa.String(length=50), nullable=True),
    sa.Column('tf_family', sa.String(length=100), nullable=True),
    sa.Column('sensing_signal', sa.String(length=200), nullable=True),
    sa.Column('active_form', sa.String(length=50), nullable=True),
    sa.Column('active_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulondb_id')
    )
    op.create_index(op.f('ix_transcription_factors_name'), 'transcription_factors', ['name'], unique=True)
    op.create_table('construct_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('construct_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('position_order', sa.Integer(), nullable=False),
    sa.Column('start_pos', sa.Integer(), nullable=True),
    sa.Column('end_pos', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['genetic_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enzyme_kinetics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reaction_id', sa.UUID(), nullable=False),
    sa.Column('ec_number', sa.String(length=20), nullable=True),
    sa.Column('km_value', sa.Float(), nullable=True),
    sa.Column('kcat_value', sa.Float(), nullable=True),
    sa.Column('optimal_temp', sa.Float(), nullable=True),
    sa.Column('optimal_ph', sa.Float(), nullable=True),
    sa.Column('temp_stability_min', sa.Float(), nullable=True),
    sa.Column('temp_stability_max', sa.Float(), nullable=True),
    sa.Column('ph_stability_min', sa.Float(), nullable=True),
    sa.Column('ph_stability_max', sa.Float(), nullable=True),
    sa.Column('organism_source', sa.String(length=200), nullable=True),
    sa.Column('brenda_id', sa.String(length=50), nullable=True),
    sa.Column('activity_curve_temp', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_curve_ph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enzyme_kinetics_ec_number'), 'enzyme_kinetics', ['ec_number'], unique=False)
    op.create_index(op.f('ix_enzyme_kinetics_reaction_id'), 'enzyme_kinetics', ['reaction_id'], unique=False)
    op.create_table('enzyme_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gene_id', sa.UUID(), nullable=False),
    sa.Column('reaction_id', sa.UUID(), nullable=False),
    sa.Column('gpr_rule', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enzyme_reactions_gene_id'), 'enzyme_reactions', ['gene_id'], unique=False)
    op.create_index(op.f('ix_enzyme_reactions_reaction_id'), 'enzyme_reactions', ['reaction_id'], unique=False)
    op.create_table('gene_regulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gene_id', sa.UUID(), nullable=False),
    sa.Column('tf_id', sa.UUID(), nullable=False),
    sa.Column('regulation_type', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('source_db', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['tf_id'], ['transcription_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_regulations_gene_id'), 'gene_regulations', ['gene_id'], unique=False)
    op.create_index(op.f('ix_gene_regulations_tf_id'), 'gene_regulations', ['tf_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('construct_id', sa.UUID(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('oxygen_level', sa.String(length=20), nullable=False),
    sa.Column('carbon_source', sa.String(length=50), nullable=False),
    sa.Column('nitrogen_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expression_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fba_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flux_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('doubling_time', sa.Float(), nullable=True),
    sa.Column('viability_score', sa.Float(), nullable=True),
    sa.Column('atp_balance', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('compute_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_construct_id'), 'simulations', ['construct_id'], unique=False)
    op.create_index(op.f('ix_simulations_status'), 'simulations', ['status'], unique=False)
    op.create_table('transporters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gene_id', sa.UUID(), nullable=False),
    sa.Column('tcdb_id', sa.String(length=20), nullable=True),
    sa.Column('tc_family', sa.String(length=100), nullable=True),
    sa.Column('substrate', sa.String(length=200), nullable=True),
    sa.Column('substrate_chebi_id', sa.String(length=20), nullable=True),
    sa.Column('transport_type', sa.String(length=50), nullable=True),
    sa.Column('vmax', sa.Float(), nullable=True),
    sa.Column('km_transport', sa.Float(), nullable=True),
    sa.Column('atp_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transporters_gene_id'), 'transporters', ['gene_id'], unique=False)
    op.create_index(op.f('ix_transporters_substrate_chebi_id'), 'transporters', ['substrate_chebi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transporters_substrate_chebi_id'), table_name='transporters')
    op.drop_index(op.f('ix_transporters_gene_id'), table_name='transporters')
    op.drop_table('transporters')
    op.drop_index(op.f('ix_simulations_status'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_construct_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_gene_regulations_tf_id'), table_name='gene_regulations')
    op.drop_index(op.f('ix_gene_regulations_gene_id'), table_name='gene_regulations')
    op.drop_table('gene_regulations')
    op.drop_index(op.f('ix_enzyme_reactions_reaction_id'), table_name='enzyme_reactions')
    op.drop_index(op.f('ix_enzyme_reactions_gene_id'), table_name='enzyme_reactions')
    op.drop_table('enzyme_reactions')
    op.drop_index(op.f('ix_enzyme_kinetics_reaction_id'), table_name='enzyme_kinetics')
    op.drop_index(op.f('ix_enzyme_kinetics_ec_number'), table_name='enzyme_kinetics')
    op.drop_table('enzyme_kinetics')
    op.drop_table('construct_parts')
    op.drop_index(op.f('ix_transcription_factors_name'), table_name='transcription_factors')
    op.drop_table('transcription_factors')
    op.drop_index(op.f('ix_reactions_bigg_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_genetic_parts_part_type'), table_name='genetic_parts')
    op.drop_index(op.f('ix_genetic_parts_name'), table_name='genetic_parts')
    op.drop_table('genetic_parts')
    op.drop_index(op.f('ix_genes_name'), table_name='genes')
    op.drop_index(op.f('ix_genes_locus_tag'), table_name='genes')
    op.drop_index('idx_gene_product_fts', table_name='genes')
    op.drop_table('genes')
    op.drop_table('constructs')
    # ### end Alembic commands ###
