"""add reference_expression_tpm and nullable construct_id

Revision ID: cfa9abee5c71
Revises: 3de98aed79d4
Create Date: 2026-09-21 11:22:01.926365
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa9abee5c71'
down_revision: Union[str, None] = '3de98aed79d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genes', sa.Column('reference_expression_tpm', sa.Float(), nullable=True))
    op.add_column('genes', sa.Column('expression_source', sa.String(length=50), nullable=True))
    op.alter_column('simulations', 'construct_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulations', 'construct_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('genes', 'expression_source')
    op.drop_column('genes', 'reference_expression_tpm')
    # ### end Alembic commands ###
